bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: Qe587H4MPVgfgfx/+CzvVcYo5+3ej5QrduehBNnU3LAWblyhqS5LUzhGrPqAl+eFSAtfdxm/e9JygyaC8vCmyxmcMEbdqsdpNFiXDbbTztQ+ePOW3WCf8Ck4MX3ffQ1HIAN67tTt2stxTYNZ60No1fw7EUdxmX75CrJO3cNI6eGBWyYbz4rTCBajQXNmHodfm/Kb351fcJba44kKNdEN35KGcF3QauV00Nk5iUkooByNIaQH4UvqlzGV3tGlXANjwOJ2hP9s6JpL/JfhkRJEQ11UvKI7wznNQavw+EzAukWOyRAKffqmzlosMlf0TzuHDKhgtD1yPSe7Qn6boCWkhD7uvmqzFusEBv/I3Xj63yevPIRLnXx+jqOMnKwGe153U64SQjBhDlDn630r0x8v9tUXtJQY1RRQ4VzSlo2HET4R7XtD10QKt3XeKk9x+wusV5D0Nc6IZpqvKBIhUxIedmKcMHfuKr3/87PrN/SjhHp+yM0alPK6MS6MCcgvrLkbinfONnHc/mwNn/JC+GmOde5UrtqB9KTd4EOA5oaZ12gFnBnaVFBHS6flt4ChDwH/gd62J+0FNCgAzEMaxoHR0WYFAXD0m/ufm+WhKV720w1T7Gf7a2iYzhIUulPntvPRqkavGaLeC5W78v9prZWFp5ILDTkY4FhzSO8DZtQwl0g=
conda_forge_output_validation: true
